name: test-simple-solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/simple-test.yml"
      - "action.yml"

jobs:
  test_linux:
    name: "Linux Test"
    runs-on: ubuntu-latest
    outputs:
        dependency_list: ${{ steps.dependency.outputs.dependency_list }}    

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: roozbehid-ic/SolutionDependencyAnalyzer
      
      - uses: roozbehid-ic/SolutionChangeDetector-Action@main
        id: dependency
        with:
          solution_path: "SolutionDependencyAnalyzer.sln"

      - name: Print list
        shell: pwsh
        run: |
              Write-Host "${{ steps.dependency.outputs.dependency_list  }}"

  test_windows:
    name: "Windows Test"
    runs-on: windows-latest
    outputs:
        dependency_list: ${{ steps.dependency.outputs.dependency_list }}    

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: roozbehid-ic/SolutionDependencyAnalyzer
      
      - uses: roozbehid-ic/SolutionChangeDetector-Action@main
        id: dependency
        with:
          solution_path: "SolutionDependencyAnalyzer.sln"

      - name: Print list
        shell: pwsh
        run: |
              Write-Host "${{ steps.dependency.outputs.dependency_list  }}"              

  next_job_linux:
    name: "next job"
    runs-on: ubuntu-latest
    needs: test_linux


    steps:
      - name: Print list
        shell: pwsh
        run: |
            Write-Host "${{ needs.test_linux.outputs.dependency_list }}"

  next_job_windows:
    name: "next job"
    runs-on: windows-latest
    needs: test_windows


    steps:
      - name: Print list
        shell: pwsh
        run: |
            Write-Host "${{ needs.test_windows.outputs.dependency_list }}"            