name: test-simple-solution

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/simple-test.yml"
      - "action.yml"

jobs:
  test:
    name: "Test: github action"
    runs-on: ubuntu-latest
    outputs:
        dependency_list: ${{ steps.dependency.outputs.dependency_list }}    

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: roozbehid-ic/SolutionDependencyAnalyzer
      
      - uses: roozbehid-ic/SolutionChangeDetector-Action@main
        id: dependency
        with:
          solution_path: "SolutionDependencyAnalyzer.sln"

      - name: Print list
        shell: pwsh
        run: |
              Write-Host ${{ steps.dependency.outputs.dependency_list  }}          
  next_job:
    name: "next job"
    runs-on: ubuntu-latest
    needs: test


    steps:
      - name: Print list
        shell: pwsh
        run: |
            Write-Host ${{ needs.test.outputs.dependency_list }}